import type { WebsiteShortcut } from "@/types/app";

export const anotherWMShortcuts: WebsiteShortcut[] = [
  {
    id: "anotherwm-watchlist",
    userId: "secret",
    title: "List",
    description: "Private watchlist saver.",
    url: "/secret/anotherwm/list",
    imageUrl: "",
    category: "List",
    displayOrder: 1,
    active: true,
    favorite: true,
    pinned: true,
    clickCount: 0,
    lastUsedAt: null,
    createdAt: "2026-07-04T00:00:00.000Z",
    updatedAt: "2026-07-04T00:00:00.000Z"
  },
  {
    id: "anotherwm-actresses",
    userId: "secret",
    title: "Actress",
    description: "Browse saved actress tags.",
    url: "/secret/anotherwm/tags?type=actress",
    imageUrl: "",
    category: "Tags",
    displayOrder: 2,
    active: true,
    favorite: true,
    pinned: true,
    clickCount: 0,
    lastUsedAt: null,
    createdAt: "2026-07-04T00:00:00.000Z",
    updatedAt: "2026-07-04T00:00:00.000Z"
  },
  {
    id: "anotherwm-genres",
    userId: "secret",
    title: "Genre",
    description: "Browse saved genre tags.",
    url: "/secret/anotherwm/tags?type=genre",
    imageUrl: "",
    category: "Tags",
    displayOrder: 3,
    active: true,
    favorite: true,
    pinned: true,
    clickCount: 0,
    lastUsedAt: null,
    createdAt: "2026-07-04T00:00:00.000Z",
    updatedAt: "2026-07-04T00:00:00.000Z"
  },
  {
    id: "anotherwm-status",
    userId: "secret",
    title: "Tag",
    description: "Browse Pending, Watched and Again.",
    url: "/secret/anotherwm/tags?type=status",
    imageUrl: "",
    category: "Tags",
    displayOrder: 4,
    active: true,
    favorite: true,
    pinned: true,
    clickCount: 0,
    lastUsedAt: null,
    createdAt: "2026-07-04T00:00:00.000Z",
    updatedAt: "2026-07-04T00:00:00.000Z"
  }
];
